services:
  postgres:
    image: postgres:16.3-alpine3.19
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./suma/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
